#!/usr/bin/env bash
# Acceptance tests for the CLAUDE.md overlay mechanism added to setup.sh.
#
# Each test runs setup.sh against a sandboxed $HOME and a snapshot of the repo,
# then asserts on the generated ~/.claude/CLAUDE.md.
#
# Run: bash tests/test-claude-md-overlay.sh
# Exits 0 on all-pass, non-zero on any failure.
#
# These tests are written BEFORE the implementation — they are expected to FAIL
# until setup.sh is updated per plans/customize-claude-md.plan.md.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PASS=0
FAIL=0
FAILED_TESTS=()

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
RESET='\033[0m'

# ── Sandbox helpers ──────────────────────────────────────────────

# Creates a fresh sandbox: temp HOME and a copy of the repo. Echoes the sandbox dir.
make_sandbox() {
  local sb
  sb=$(mktemp -d -t farty-claude-md-test.XXXXXX)
  mkdir -p "$sb/home"
  cp -R "$REPO_ROOT" "$sb/repo"
  # Strip any inherited state from the copy so tests start clean.
  rm -rf "$sb/repo/.git"
  # Re-init a minimal git repo so `git check-ignore` works in AC-6.
  (cd "$sb/repo" && git init --quiet && git add -A && git -c user.email=t@t -c user.name=t commit --quiet -m init) >/dev/null
  echo "$sb"
}

# Runs setup.sh inside a sandbox with HOME pointing at sandbox/home.
# Forwards any extra args to setup.sh. Returns setup's exit code.
run_setup() {
  local sb="$1"; shift
  HOME="$sb/home" bash "$sb/repo/setup.sh" "$@" >"$sb/setup.out" 2>"$sb/setup.err"
}

# ── Assertions ───────────────────────────────────────────────────

assert_file_exists() {
  [[ -f "$1" ]] || { echo "  FAIL: expected file to exist: $1"; return 1; }
}

assert_not_symlink() {
  [[ ! -L "$1" ]] || { echo "  FAIL: expected NOT a symlink: $1"; return 1; }
}

assert_is_symlink() {
  [[ -L "$1" ]] || { echo "  FAIL: expected a symlink: $1"; return 1; }
}

assert_contains() {
  local file="$1" needle="$2"
  if ! grep -qF -- "$needle" "$file"; then
    echo "  FAIL: file $file did not contain: $needle"
    return 1
  fi
}

assert_not_contains() {
  local file="$1" needle="$2"
  if grep -qF -- "$needle" "$file"; then
    echo "  FAIL: file $file unexpectedly contained: $needle"
    return 1
  fi
}

# ── Test runner ──────────────────────────────────────────────────

run_test() {
  local name="$1"
  printf "→ %s\n" "$name"
  if "$name"; then
    PASS=$((PASS + 1))
    printf "  ${GREEN}PASS${RESET}\n"
  else
    FAIL=$((FAIL + 1))
    FAILED_TESTS+=("$name")
    printf "  ${RED}FAIL${RESET}\n"
  fi
}

# ── Test cases ───────────────────────────────────────────────────

# AC-1: With no CLAUDE.local.md, setup writes ~/.claude/CLAUDE.md as a real
# file containing the generated header and the full base content.
test_baseline_only_no_overlay() {
  local sb claude_md
  sb=$(make_sandbox)
  rm -f "$sb/repo/CLAUDE.local.md"
  run_setup "$sb" --links-only --quiet || { echo "  setup.sh exited non-zero"; cat "$sb/setup.err"; return 1; }
  claude_md="$sb/home/.claude/CLAUDE.md"
  assert_file_exists "$claude_md"             || return 1
  assert_not_symlink "$claude_md"             || return 1
  assert_contains    "$claude_md" "GENERATED BY setup.sh" || return 1
  # A line that's stable in the canonical CLAUDE.md.
  assert_contains    "$claude_md" "Farty Bobo" || return 1
}

# AC-2: With CLAUDE.local.md present, generated file contains the overlay
# content AND the separator marker.
test_overlay_concatenated() {
  local sb claude_md
  sb=$(make_sandbox)
  printf 'LOCAL_OVERLAY_MARKER_XYZ\n' > "$sb/repo/CLAUDE.local.md"
  run_setup "$sb" --links-only --quiet || { echo "  setup.sh exited non-zero"; cat "$sb/setup.err"; return 1; }
  claude_md="$sb/home/.claude/CLAUDE.md"
  assert_file_exists "$claude_md"                       || return 1
  assert_contains    "$claude_md" "Farty Bobo"          || return 1
  assert_contains    "$claude_md" "LOCAL_OVERLAY_MARKER_XYZ" || return 1
  assert_contains    "$claude_md" "User customizations from CLAUDE.local.md" || return 1
}

# AC-3: A pre-existing symlink at ~/.claude/CLAUDE.md is replaced with a real file.
test_stale_symlink_replaced() {
  local sb claude_md
  sb=$(make_sandbox)
  mkdir -p "$sb/home/.claude"
  ln -s "$sb/repo/CLAUDE.md" "$sb/home/.claude/CLAUDE.md"
  assert_is_symlink "$sb/home/.claude/CLAUDE.md" || return 1
  run_setup "$sb" --links-only --quiet || { echo "  setup.sh exited non-zero"; cat "$sb/setup.err"; return 1; }
  claude_md="$sb/home/.claude/CLAUDE.md"
  assert_file_exists "$claude_md"   || return 1
  assert_not_symlink "$claude_md"   || return 1
}

# AC-4: A pre-existing real (non-symlink) file with hand-edited content is
# backed up before being overwritten.
test_prior_real_file_backed_up() {
  local sb claude_md backup
  sb=$(make_sandbox)
  mkdir -p "$sb/home/.claude"
  printf 'OLD_HAND_EDITED_MARKER\n' > "$sb/home/.claude/CLAUDE.md"
  run_setup "$sb" --links-only --quiet || { echo "  setup.sh exited non-zero"; cat "$sb/setup.err"; return 1; }
  claude_md="$sb/home/.claude/CLAUDE.md"
  assert_file_exists  "$claude_md"                              || return 1
  assert_not_contains "$claude_md" "OLD_HAND_EDITED_MARKER"     || return 1
  # Backup file should exist with the old content.
  backup=$(find "$sb/home/.claude" -maxdepth 1 -name 'CLAUDE.md.backup-*' -type f 2>/dev/null | head -1)
  [[ -n "$backup" ]] || { echo "  FAIL: expected a CLAUDE.md.backup-* file"; return 1; }
  assert_contains "$backup" "OLD_HAND_EDITED_MARKER" || return 1
}

# AC-5: --links-only mode regenerates the composite (per-session self-heal
# must pick up overlay edits).
test_links_only_regenerates() {
  local sb claude_md
  sb=$(make_sandbox)
  printf 'SELFHEAL_MARKER\n' > "$sb/repo/CLAUDE.local.md"
  run_setup "$sb" --links-only --quiet || { echo "  setup.sh exited non-zero"; cat "$sb/setup.err"; return 1; }
  claude_md="$sb/home/.claude/CLAUDE.md"
  assert_file_exists "$claude_md"                 || return 1
  assert_contains    "$claude_md" "SELFHEAL_MARKER" || return 1
}

# AC-6: CLAUDE.local.md is ignored by git.
test_claude_local_md_gitignored() {
  # Run against the actual repo, not a sandbox copy — the .gitignore is what's under test.
  ( cd "$REPO_ROOT" && git check-ignore -q CLAUDE.local.md ) \
    || { echo "  FAIL: CLAUDE.local.md is not gitignored at $REPO_ROOT/.gitignore"; return 1; }
}

# ── Run ──────────────────────────────────────────────────────────

run_test test_baseline_only_no_overlay
run_test test_overlay_concatenated
run_test test_stale_symlink_replaced
run_test test_prior_real_file_backed_up
run_test test_links_only_regenerates
run_test test_claude_local_md_gitignored

printf "\n${GREEN}%d passed${RESET}, ${RED}%d failed${RESET}\n" "$PASS" "$FAIL"
if (( FAIL > 0 )); then
  printf "Failed tests:\n"
  for t in "${FAILED_TESTS[@]}"; do printf "  - %s\n" "$t"; done
  exit 1
fi
